[tool.poetry]
name = "triangledraw"
version = "0.1.0"
description = ""
authors = ["Jeff Tipps <jeff.tipps@ni.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.8.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
